#!/bin/bash

# Check that lazydocker is installed
if ! command -v lazydocker &>/dev/null; then
  echo "lazydocker could not be found"
else
  CURRENT="$(lazydocker --version | awk '/^Version:/{print $2}')"
  echo "Current version: ${CURRENT}"
fi

# Check latest version
VERSION=$(curl -s https://api.github.com/repos/jesseduffield/lazydocker/releases/latest | grep tag_name | cut -d '"' -f 4)
VERSION_CLEAN=$(echo "${VERSION}" | sed 's/v//')

if [[ "${CURRENT}" == "${VERSION_CLEAN}" ]]; then
  echo "Latest version ${VERSION} already installed" && exit
else
  echo "New version is available: ${VERSION}"
fi

# Exit script if dry run is given
if [[ "$1" == "--check" ]]; then
  exit
fi

# Prompt user to continue
read -r -p "Do you want to continue installing new version? [y/N] " response
if [[ ! "${response}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
  exit
fi

# map different architecture variations to the available binaries
ARCH=$(uname -m)
case $ARCH in
    i386|i686) ARCH=x86 ;;
    armv6*) ARCH=armv6 ;;
    armv7*) ARCH=armv7 ;;
    aarch64*) ARCH=arm64 ;;
esac

FILENAME="lazydocker_${VERSION_CLEAN}_$(uname -s)_${ARCH}.tar.gz"
URI="https://github.com/jesseduffield/lazydocker/releases/download/${VERSION}/${FILENAME}"
DOWNLOAD_DIR="/tmp/"

# Download latest version
echo "Downloading and installing new version..."
wget --quiet "${URI}" -P "${DOWNLOAD_DIR}"

# Extract downloaded version
tar -xzf "${DOWNLOAD_DIR}${FILENAME}" -C "${DOWNLOAD_DIR}" lazydocker

# Install to ~/utils (or update existing location)
if command -v lazydocker &>/dev/null; then
  INSTALL_DIR="$(dirname "$(command -v lazydocker)")"
else
  INSTALL_DIR="${HOME}/utils"
fi

install -Dm 755 "${DOWNLOAD_DIR}lazydocker" -t "${INSTALL_DIR}"

# Delete downloaded files
rm "${DOWNLOAD_DIR}${FILENAME}" "${DOWNLOAD_DIR}lazydocker"

# Print new version
echo "New version installed: $(lazydocker --version | awk '/^Version:/{print $2}')"
